### ISSUE TITLE
Is this a wrapper around the C hdf5 libraries or an independent implementation? Possible to support streaming?

### ISSUE THREAD

**Issue by julian1** [stainless-steel/hdf5-sys#4]
Sorry, this is more a question than an issue, but Github doesn't provide a better alternative,than using the issues page.

The C implementation of the HDF5 protocol is strongly orientated around the idea of constructing HDF5 files on a filesystem.

Instead, I would like to directly write a file-descriptor with HDF5 objects using append only write methods.

This would allow me to encode and stream an HDF5 file over HTTP - and without  the need for a (large) intermediate filesystem cache on the server.

Is there any insight into whether hdf5-sys would be amendable to this kind of modification, or suggestions on where to start experimenting? The code looks a lot simpler and cleaner than the C library.

Cheers,

**Comment by julian1** [comment]
Ok, it looks like it's a set of bindings. 

I was misled because https://libraries.io/cargo/hdf5-sys lists libc but not hdf5 c libraries. I guess because the dependency is pulled in directly via the git submodule.

**Comment by gustavla** [comment]
I would start looking through the HDF5 API specification (https://www.hdfgroup.org/HDF5/doc/RM/RM_H5Front.html), to see if they offer what you need. As far as I remember, most HDF5 functions take file names and not file handlers, so not sure how it could be done. The specs are huge though (which is probably why the C implementation is the only mature one as far as I know), so there might be functions in there somewhere to do this.
